kind: pipeline
type: docker
name: linux_amd64

steps:    
  - name: push-linux-amd64-image
    image: plugins/docker
    settings:
      repo: programzheng/language-repository
      dockerfile: Dockerfile
      username:
        from_secret: PUSH_LINUX_AMD64_IMAGE_USERNAME
      password:
        from_secret: PUSH_LINUX_AMD64_IMAGE_PASSWORD

  - name: ssh-remote-host-by-drone-ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_REMOTE_HOST
      username:
        from_secret: SSH_REMOTE_USERNAME
      key:
        from_secret: SSH_REMOTE_KEY
      port:
        from_secret: SSH_REMOTE_PORT
      script:
        - cat /root/drone_rsa