kind: pipeline
type: docker
name: linux_amd64

steps:
  - name: build-linux-amd64
    image: golang:1.16
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
    - make build
    
  - name: push-linux-amd64-image
    image: plugins/docker
    settings:
      registry: registry.hub.docker.com
      repo: hub.docker.com/repository/docker/programzheng/language-repository
      username: programzheng
      password:
        - from_secret: docker_linux_amd64_password