version: '3'

services:
    #api
    api:
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: always
      env_file:
        - .env
      ports:
        - ${LOCAL_PORT}:${APP_PORT}
      networks:
        - backend

networks:
  backend:
    external: true